[package]
name = "tosts"
version = "0.1.0"
edition = "2024"

[dependencies]
clap={version="4", features=["derive"]}
tracing-subscriber="0.3.22"
tracing="0.1.44"
rlimit="0.10.2"

wait-timeout="0.2.1"
indicatif = "0.18"